baseURL = 'https://german-driving-prep.github.io'
languageCode = 'en-us'
title = 'German Driving Prep'
theme = 'stack'

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage = 'en'

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[languages.en]
languageName = 'English'
title = 'German Driving Prep'
weight = 1
[languages.en.params.sidebar]
subtitle = 'Your guide to passing the German driving test'

[services.disqus]
shortname = 'hugo-theme-stack'

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 10

[permalinks]
post = '/p/:slug/'
page = '/:slug/'

[params]
mainSections = ['post']
featuredImageField = 'image'
rssFullContent = true
favicon = ''

[params.footer]
since = 2023
customText = ''

[params.dateFormat]
published = 'Jan 02, 2006'
lastUpdated = 'Jan 02, 2006 15:04 MST'

[params.sidebar]
emoji = '🍥'
subtitle = 'Your guide to passing the German driving test'
[params.sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.png'

[params.article]
math = false
toc = true
readingTime = true
[params.article.license]
enabled = true
default = 'Licensed under CC BY-NC-SA 4.0'

[params.comments]
enabled = true
provider = 'disqus'

[params.widgets]
homepage = [
    { type = 'search' },
    { type = 'archives', params = { limit = 5 } },
    { type = 'categories', params = { limit = 10 } },
    { type = 'tag-cloud', params = { limit = 10 } }
]
page = [
    { type = 'toc' }
]

[params.opengraph.twitter]
site = ''
card = 'summary_large_image'

[params.defaultImage.opengraph]
enabled = false
local = false
src = ''

[params.colorScheme]
toggle = true
default = 'auto'

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
[[menu.main]]

[related]
includeNewer = true
threshold = 60
toLower = false
[[related.indices]]
name = 'tags'
weight = 100
[[related.indices]]
name = 'categories'
weight = 200

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['[', ']'], ['$', '$']]
inline = [['(', ')']]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
